# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MW2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MW2018
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    pod 'MASFoundation'
    pod 'MASUI'
    pod 'MASConnecta'
    pod 'MASIdentityManagement'
    pod 'MASStorage'

end

target 'MW2018 SSO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MW2018 SSO
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    pod 'MASFoundation'
    pod 'MASUI'
    pod 'MASConnecta'
    pod 'MASIdentityManagement'
    pod 'MASStorage'

end
